name: 'React Native Version'
description: 'Composite Action for React Native Version Bump and GitHub Release'
author: 'Nabeel Shakeel'
branding:
  icon: check-circle
  color: blue

inputs:
  repo_token:
    description: "GitHub secret token"
    required: true
  supported_parameters:
    description: "A key-value pair of supported parameters"
    required: false
  
runs:
  using: "composite"
  steps:    
    - name: Automated Version Bump
      uses: paramsinghvc/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{ inputs.repo_token }}
      with:
        tag-prefix: ${{ fromJSON(inputs.supported_parameters).tag-prefix }}
        tag-suffix: ${{ inputs.supported_parameters.tag-suffix }}

    - name: Sync React Native version with package.json Version
      run: npx react-native-version
      shell: bash

    - name: Commit Version Sync Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: ${{ github.event.inputs.commit-message }}

    - name: Create Automated Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ inputs.repo_token }}
        automatic_release_tag: ${{ inputs.supported_parameters.automatic_release_tag }}